# ---------- Minecraft Server Configuration -------------
[mc]
dir = "mc/server-1-20-10"
jar = "paper.jar" # The initial server file
min_gb = 4
max_gb = 4
screen_name = "minecraft_survival_server" # Choose a custom name for the screen

